services:
  # Angular Frontend (Not final decision)
  frontend:
    hostname: angular_frontend
    container_name: angular_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/frontend
    environment:
      TZ: UTC
    command: ["sh", "-c", "npx -y http-server /frontend -p 4200 -a 0.0.0.0"]
    restart: unless-stopped
    depends_on:
      - backend

  # Symfony Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: symfony_backend
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/var/www
      - backend_vendor:/var/www/vendor
      - backend_var:/var/www/var
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      APP_ENV: dev
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=17&charset=utf8"
    depends_on:
      database:
        condition: service_healthy

  # PostgreSQL Database
  database:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  backend_vendor:
  backend_var:
